/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        // AliTché Custom Color Palette
        "on-primary-container": "#c9d9ff",
        "on-tertiary-container": "#d1d8f3",
        "surface-tint": "#1f5cb6",
        "on-secondary": "#ffffff",
        "primary-fixed-dim": "#adc6ff",
        "tertiary-container": "#575e75",
        "surface-dim": "#d8dadc",
        "on-surface-variant": "#424752",
        "primary-container": "#1f5cb6",
        "inverse-on-surface": "#eff1f3",
        "inverse-primary": "#adc6ff",
        "on-tertiary": "#ffffff",
        "surface-subtle": "#F5F8FC",
        "on-primary-fixed": "#001a41",
        "secondary-container": "#40c2fd",
        "primary-fixed": "#d8e2ff",
        "surface-container-low": "#f2f4f6",
        "on-secondary-fixed": "#001e2c",
        "surface-container-high": "#e6e8ea",
        "on-primary": "#ffffff",
        "success-emerald": "#10B981",
        "outline": "#737783",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "secondary-fixed-dim": "#7bd0ff",
        "secondary": "#00668a",
        "surface-container": "#eceef0",
        "tertiary-fixed": "#dae2fd",
        "background": "#f7f9fb",
        "surface-container-highest": "#e0e3e5",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#004493",
        "secondary-fixed": "#c4e7ff",
        "primary": "#004494",
        "surface-container-lowest": "#ffffff",
        "inverse-surface": "#2d3133",
        "error": "#ba1a1a",
        "on-tertiary-fixed-variant": "#3f465c",
        "on-error-container": "#93000a",
        "tertiary-fixed-dim": "#bec6e0",
        "on-tertiary-fixed": "#131b2e",
        "outline-variant": "#c2c6d4",
        "tertiary": "#3f475c",
        "on-error": "#ffffff",
        "surface": "#f7f9fb",
        "on-background": "#191c1e",
        "text-muted": "#475569",
        "on-secondary-fixed-variant": "#004c69",
        "on-surface": "#191c1e",
        "on-secondary-container": "#004d6a",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "stack-lg": "32px",
        "margin-desktop": "48px",
        "container-max": "1280px",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Montserrat", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-md": ["Montserrat", "sans-serif"],
        "display-lg": ["Montserrat", "sans-serif"],
        "headline-lg": ["Montserrat", "sans-serif"],
      },
      fontSize: {
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "headline-lg-mobile": ["28px", { lineHeight: "36px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "label-md": ["14px", { lineHeight: "20px", letterSpacing: "0.01em", fontWeight: "600" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
}
